[package]
name = "holdem-solver-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
holdem-solver-icm = { path = "../icm" }
holdem-solver-core = { path = "../solver" }
serde_json = "1.0.114"

[[bin]]
name = "holdem-solver"
path = "src/main.rs"
